title: Lindsey Rickerman
author:
  name: Lindsey Rickerman
  email: lindsey.rickerman@health.ny.gov
description: lindsey.rickerman@health.ny.gov
theme: minima


collections:
  wiki:
    output: true
    permalink: /:collection/:title:output_ext